---
title: "Inning Simulation"
author: "Devin Basley"
date: "2024-04-21"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# This simulation guesses YRFI almsot every time; 50% Accuracy


# Load Data

```{r}

# Load Data
statcast_2023_first_inning <- read_csv("statcast_2023_first_inning.csv")


#
statcast_2023_first_inning$on_1b[is.na(statcast_2023_first_inning$on_1b)] <- "woo"
statcast_2023_first_inning$on_2b[is.na(statcast_2023_first_inning$on_2b)] <- "woo"
statcast_2023_first_inning$on_3b[is.na(statcast_2023_first_inning$on_3b)] <- "woo"

#statcast_2023_first_inning <- statcast_2023_first_inning[rev(1:nrow(statcast_2023_first_inning)), ]

# Vector of Events that only include action events
# Balls and Strikes that DO NOT result in walks or strikeouts excluded
included_events <- c("double", "field_out", "force_out",
                     "home_run", "sac_fly", "strikeout", "walk",
                     "double_play", "fielders_choice",
                     "sac_fly_double_play",
                     "strikeout_double_play", "field_error",
                     "fielders_choice_out", "hit_by_pitch", "sac_bunt", "single",
                     "triple")


# Filter statcast data for only action events
statcast_2023_first_inning <- statcast_2023_first_inning %>%
  filter(events %in% included_events) %>%
  mutate(runs_before = away_score + home_score)


# Summarize half inning totals
half_innings <- statcast_2023_first_inning %>%
  group_by(inning_topbot) %>%
  summarize(outs_inning = sum(outs_when_up),
            runs_inning = sum(post_bat_score),
            runs_start = first(runs_before),
            max_runs = runs_inning + runs_start)




statcast_2023_first_inning <- statcast_2023_first_inning %>%
  inner_join(half_innings, by = "inning_topbot") %>%
  mutate(runs_roi = max_runs - runs_before)


# Start Game State compuation
statcast_2023_first_inning <- statcast_2023_first_inning %>%
  mutate(bases = paste0(
    if_else(on_1b == "woo", 0, 1),
    if_else(on_2b == "woo", 0, 1),
    if_else(on_3b == "woo", 0, 1)))
    

# statcast_2023_first_inning <- statcast_2023_first_inning %>%
#   mutate(
#     is_runner1 = as.numeric(
#       on_1b == 1 | batter == 1
#     ),
#     is_runner2 = as.numeric(
#       on_1b == 2 | on_2b == 2 | 
#         batter == 2
#     ),
#     is_runner3 = as.numeric(
#       on_1b== 3 | on_2b == 3 |
#         on_3b == 3 | batter == 3
#     ),
#     new_bases = paste0(is_runner1, is_runner2, is_runner3))


# Compute Pre and Post AB State
statcast_2023_first_inning <- statcast_2023_first_inning %>%
  mutate(state = paste(bases, outs_when_up),
        new_state = case_when(
          inning_topbot != lag(inning_topbot) ~ NA_character_,
           TRUE ~ lag(state)
         ))



# Reverse Data
statcast_2023_first_inning <- statcast_2023_first_inning[rev(1:nrow(statcast_2023_first_inning)), ]


statcast_2023_first_inning$new_state[is.na(statcast_2023_first_inning$new_state)] <- "woo"

statcast_2023_first_inning <- statcast_2023_first_inning %>%
  mutate(new_state = str_replace(new_state, "woo", "3"))



# End of First Inning Summary
end_inning_data <- statcast_2023_first_inning %>%
  dplyr::select(c(game_date, game_pk, player_name, player_name, batter, post_home_score, post_away_score, inning_topbot, away_team, home_team)) %>%
  group_by(game_pk) %>%
  mutate(away_runs = max(post_away_score),
            home_runs = max(post_home_score),
            total_runs = away_runs + home_runs,
            home = home_team,
            away = away_team) %>%
  ungroup() 
  
# Home team indicator variable
end_inning_data <- end_inning_data %>%
  mutate(is_home = ifelse(inning_topbot == "Bot", 1, 0)) 


end_inning_data <- end_inning_data %>%
  mutate(team = if_else(is_home == 1, home, away),
         runs = if_else(is_home == 1, home_runs, away_runs)) 

# Selecting required columns
new_dataset <- end_inning_data %>%
  dplyr::select(game_pk, team, runs, is_home, player_name)

half_inning_data <- end_inning_data %>%
  group_by(game_pk, is_home) %>%
  summarise(team = first(team),
            runs = if_else(first(is_home) == 1, max(home_runs), max(away_runs)),
            pitcher = first(player_name),
            PA = n_distinct(batter),
            date = first(game_date)) %>%
  ungroup()

team_info <- end_inning_data %>%
  group_by(game_pk) %>%
  summarise(home_team = first(home),
            away_team = first(away)) %>%
  ungroup()

# Merge team information with half_inning_data
half_inning_data <- half_inning_data %>%
  left_join(team_info, by = "game_pk")


game_summary <- half_inning_data %>%
  group_by(game_pk) %>%
  summarize(
    home_team = first(home_team),
    away_team = first(away_team),
    home_runs = sum(if_else(is_home == 1, runs, 0)),
    away_runs = sum(if_else(is_home == 0, runs, 0)),
    total_runs = if_else(home_runs + away_runs == 0, "NRFI", "YRFI"),
    date = first(date)
  ) %>%
  ungroup()


# mlb_team_run_rate <- half_inning_data %>%
#   group_by(team) %>%
#   summarise(
#     run_rate = mean(runs)
#   ) %>%
#   ungroup()

mlb_team_run_rate <- half_inning_data %>%
  group_by(team) %>%
  summarise(
    run_rate_away = mean(if_else(is_home == 0, runs, NA), na.rm = TRUE),
    run_rate_home = mean(if_else(is_home == 1, runs, NA), na.rm = TRUE)
  ) %>%
  ungroup()

# Plot Histogram of away team scoring rate
mlb_team_run_rate %>%
  ggplot(aes(x = run_rate_away)) +
  geom_histogram(bins = 25) +
  geom_density() +
  labs(x = "Run Scoring Rate",
       y = "Count",
       title = "Distribution of Team Scoring Rate") +
  theme_bw()

# Plot Histogram of home team scoring rate
mlb_team_run_rate %>%
  ggplot(aes(x = run_rate_home)) +
  geom_histogram(bins = 25) +
  geom_density() +
  labs(x = "Run Scoring Rate",
       y = "Count",
       title = "Distribution of Team Scoring Rate") +
  theme_bw()



# Home run rate as numeric variable
mlb_team_run_rate$run_rate_home <- as.numeric(mlb_team_run_rate$run_rate_home)
# Away run rate as numeric variable
mlb_team_run_rate$run_rate_away <- as.numeric(mlb_team_run_rate$run_rate_away)

library(MASS)
# Estimate prior shape and rate for home gamma distribution
home_run_rate_gamma <- fitdistr(mlb_team_run_rate$run_rate_home, dgamma, 
                               list(shape = 5, rate = 4))
# Estimate prior shape and rate for away gamma distribution
away_run_rate_gamma <- fitdistr(mlb_team_run_rate$run_rate_away, dgamma, 
                               list(shape = 5, rate = 4))


# Home Shape and Rate estimates
home_prior_shape <- home_run_rate_gamma$estimate[1]
home_prior_rate <- home_run_rate_gamma$estimate[2]

# Away Shape and Rate estimates
away_prior_shape <- away_run_rate_gamma$estimate[1]
away_prior_rate <- away_run_rate_gamma$estimate[2]



# Displays Home Prior Shape and Prior Rate
cat("The home prior shape is", round(home_prior_shape, 2),"\n")
cat("The home prior rate is", round(home_prior_rate, 2), "\n")

# Displays Away Prior Shape and Prior Rate
cat("The away prior shape is", round(away_prior_shape, 2),"\n")
cat("The away prior rate is", round(away_prior_rate, 2))


# # Create a summary table with total goals and matches plays
# summary_table <- half_inning_data %>%
#   group_by(team) %>%
#   summarize(total_runs = sum(runs),
#             games_played = n())

summary_table <- half_inning_data %>%
  group_by(team) %>%
  summarize(
    total_runs_home = sum(if_else(is_home == 1, runs, 0)),
    total_runs_away = sum(if_else(is_home == 0, runs, 0)),
    total_home_games = sum(if_else(is_home == 1, 1, 0)),
    total_away_games = sum(if_else(is_home == 0, 1, 0))
  ) %>%
  ungroup()

# Add columns for home prior shape and rate hyperparameters
summary_table$prior_shape_home <- home_prior_shape
summary_table$prior_rate_home <- home_prior_rate
# Add columns for away prior shape and rate hyperparameters
summary_table$prior_shape_away <- away_prior_shape
summary_table$prior_rate_away <- away_prior_rate


# Compute the updated quantities for the home posterior shape and rate parameters
summary_table$posterior_shape_home <- summary_table$prior_shape_home + summary_table$total_runs_home
summary_table$posterior_rate_home <- summary_table$prior_rate_home + summary_table$total_home_games
# Compute the updated quantities for the away posterior shape and rate parameters
summary_table$posterior_shape_away <- summary_table$prior_shape_away + summary_table$total_runs_away
summary_table$posterior_rate_away <- summary_table$prior_rate_away + summary_table$total_away_games


# Compute Home Gamma mean and Gamma mode from the summary table
gamma_mean_mode_table <- summary_table %>%
  mutate(gamma_mean_home = posterior_shape_home / posterior_rate_home,
         gamma_mode_home = (posterior_shape_home - 1) / posterior_rate_home,
         gamma_mean_away = posterior_shape_away / posterior_rate_away,
         gamma_mode_away = (posterior_shape_home - 1) / posterior_rate_away) 


# Create subset of team and gamma mean, mode
gamma_mean_mode_table <- subset(gamma_mean_mode_table, 
                                select = -c(total_runs_home, total_runs_away, 
                                            total_away_games,total_home_games ,prior_rate_home, 
                                            prior_shape_home, posterior_rate_home,
                                            posterior_shape_home, prior_rate_away, prior_shape_away,
                                            posterior_rate_away))

# Put in descending order of Home Gamma mode
gamma_mean_mode_table <- gamma_mean_mode_table[order(-gamma_mean_mode_table$gamma_mode_home), ]

# Display Gamma mean and mode table
print(gamma_mean_mode_table)



# Compute 80% credible intervals
summary_table <- summary_table %>%
  mutate(lower_int_home = qgamma(0.1, posterior_shape_home),
         upper_int_home = qgamma(0.9, posterior_shape_home),
         lower_int_away = qgamma(0.1, posterior_shape_away),
         upper_int_away = qgamma(0.9, posterior_shape_away))

# summary_table <- summary_table %>%
#   dplyr::select(-c(lower_int, upper_int))


# Visualize Home Team posterior Shape with their credible intervals
summary_table %>%
  ggplot(aes(x = reorder(team, posterior_shape_home), y = posterior_shape_home)) +
  geom_point() +
  geom_errorbar(aes(ymin = lower_int_home, ymax = upper_int_home, color = "red")) +
  labs(x = "Team", y = "Posterior Shape",
       title = "MLB Home Team Posterior Shape with 80% Credible Intervals",
       color = "Credible Intervals") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

# Visualize Away Team posterior Shape with their credible intervals
summary_table %>%
  ggplot(aes(x = reorder(team, posterior_shape_away), y = posterior_shape_away)) +
  geom_point() +
  geom_errorbar(aes(ymin = lower_int_away, ymax = upper_int_away, color = "red")) +
  labs(x = "Team", y = "Posterior Shape",
       title = "MLB Away Team Posterior Shape with 80% Credible Intervals",
       color = "Credible Intervals") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))



summary_table <- summary_table %>%
  mutate(posterior_probs_home = 1 - pgamma(1, posterior_shape_home, posterior_rate_home),
         prior_probs_home = 1 - pgamma(1, prior_shape_home, prior_rate_home),
         posterior_odds_home = posterior_probs_home / (1 - posterior_probs_home),
         prior_odds_home = prior_probs_home / (1 - prior_probs_home),
         Bayes_Factor_home = posterior_odds_home / prior_odds_home,
         posterior_probs_away = 1 - pgamma(1, posterior_shape_away, posterior_rate_away),
         prior_probs_away = 1 - pgamma(1, prior_shape_away, prior_rate_away),
         posterior_odds_away = posterior_probs_away / (1 - posterior_probs_away),
         prior_odds_away = prior_probs_away / (1 - prior_probs_away),
         Bayes_Factor_away = posterior_odds_away / prior_odds_away)


# Create Bayes Factor Table with team, posterior probability and bayes factor
Bayes_Factor_Table <- subset(summary_table, 
                             select = c(team, posterior_probs_home, Bayes_Factor_home,
                                        posterior_probs_away, Bayes_Factor_away))


# Put Bayes Factor table in descending order of Bayes Factor
Bayes_Factor_Table <- Bayes_Factor_Table[order(-Bayes_Factor_Table$Bayes_Factor_home), ]
                             

# Display Bayes Factor Table
print(Bayes_Factor_Table)



sim_team_runs <- function(n_games, shape, rate) {
  
  # First draw the values for the scoring rate from the posterior distribution
  # using given shape and rate parameters:
  games_rates <- rgamma(n_games, shape, rate)
  
  # And now generate the number of goals scored using the Poisson distribution
  game_runs <- rpois(n_games, games_rates)
  
  # Return these goals:
  return(game_runs)
  
}


```






# Account For Home and Away Posteriors

```{r}
# Set-up number of sims as a global parameter:
N_SIMS <- 1000

# Put it all together:
pred_game_outcomes <- 
  map_dfr(1:nrow(game_summary),
          function(game_i) {
            
            # First gather the match_i data:
            game_i_data <- game_summary[game_i,]
            
            # Next, we'll get the home team parameters:
            home_params <- if (game_i_data$home_team %in% summary_table$team) {
              summary_table %>%
                filter(team == game_i_data$home_team) %>%
                dplyr::select(c(posterior_shape_home, posterior_rate_home)) %>%
                unlist() %>%
                as.numeric()
            } else {
              c(prior_shape_home, prior_rate_home)
            }
            
            # Repeat for the away team:
            away_params <- if (game_i_data$away_team %in% summary_table$team) {
              summary_table %>%
                filter(team == game_i_data$away_team) %>%
                dplyr::select(c(posterior_shape_away, posterior_rate_away)) %>%
                unlist() %>%
                as.numeric()
            } else {
              c(prior_shape_away, prior_rate_away)
            }
            
            # And now use the function from part (a) to generate run values
            # for home team:
            home_runs <- sim_team_runs(N_SIMS, home_params[1], home_params[2])
            
            # Repeat for away:
            away_runs <- sim_team_runs(N_SIMS, away_params[1], away_params[2])
            
            # Determine pairwise whether or not home_win, away_win, or tie across
            # the N_SIMS:
            sim_outcomes <- ifelse(away_runs + home_runs == 0, "NRFI","YRFI")
            
            # Return a tibble that has the match id, actual outcome, and predicted probs
            # for each of the outcomes:
            tibble(game_pk = game_i_data$game_pk,
                   outcome = game_i_data$total_runs,
                   NRFI_win_prob = length(which(sim_outcomes == "NRFI")) / N_SIMS,
                   NRFI_lose_prob = length(which(sim_outcomes == "YRFI")) / N_SIMS)
            
          })

pred_game_outcomes

```


# Assess NRFI Simulation

```{r}
# Make predictions based on the predicted probabilities for each match
predicted_outcomes <- pred_game_outcomes %>%
  mutate(predicted_outcome = case_when(
    NRFI_win_prob > NRFI_lose_prob ~ "NRFI",
    NRFI_lose_prob > NRFI_win_prob ~ "YRFI",
    TRUE ~ NA_integer_
  ))

table(predicted_outcomes$predicted_outcome)

# Compare predicted outcomes with actual outcomes
correct_predictions <- sum(predicted_outcomes$predicted_outcome == predicted_outcomes$outcome, na.rm = TRUE)

# Calculate overall accuracy
accuracy <- correct_predictions / nrow(predicted_outcomes) * 100

# Print the overall accuracy
cat("Overall accuracy of Bayesian simulations:", accuracy, "%")


```



# Naive Assessment

```{r}
# Count the number of matches classified as home win
NRFI_win_count <- sum(pred_game_outcomes$outcome == 1)

# Count the total number of matches
total_games <- nrow(pred_game_outcomes)

# Calculate accuracy by classifying every match as a home win
accuracy_NRFI_win <- NRFI_win_count / total_games * 100

# Print the accuracy
cat("Accuracy from classifying every game as a NRFI:", accuracy_NRFI_win, "%")



```





# Possibly Include Pitcher Posterior

```{r}


# # # Set-up number of sims as a global parameter:
# N_SIMS <- 1000
# 
# # Put it all together:
# pred_game_outcomes <-
#   map_dfr(1:nrow(game_summary),
#           function(game_i) {
# 
#             # First gather the match_i data:
#             game_i_data <- game_summary[game_i,]
# 
#             # Retrieve home and away run rate parameters
#             home_team_params <- summary_table %>%
#               filter(team == game_i_data$home_team) %>%
#               select(posterior_shape_home, posterior_rate_home) %>%
#               unlist() %>%
#               as.numeric()
# 
#             away_team_params <- summary_table %>%
#               filter(team == game_i_data$away_team) %>%
#               select(posterior_shape_away, posterior_rate_away) %>%
#               unlist() %>%
#               as.numeric()
# 
#             # Retrieve starting pitcher parameters for home team
#             home_pitcher_params <- pitcher_info %>%
#               filter(team == game_i_data$home_team) %>%
#               select(posterior_shape, posterior_rate) %>%
#               unlist() %>%
#               as.numeric()
# 
#             # Retrieve starting pitcher parameters for away team
#             away_pitcher_params <- pitcher_info %>%
#               filter(team == game_i_data$away_team) %>%
#               select(posterior_shape, posterior_rate) %>%
#               unlist() %>%
#               as.numeric()
# 
#             # Combine home and pitcher parameters
#             home_combined_params <- c(home_team_params, home_pitcher_params)
#             away_combined_params <- c(away_team_params, away_pitcher_params)
# 
#             # And now use the function from part (a) to generate run values
#             # for home team with combined parameters:
#             home_runs <- sim_team_runs(N_SIMS, home_combined_params[1], home_combined_params[2])
# 
#             # Repeat for away team with combined parameters:
#             away_runs <- sim_team_runs(N_SIMS, away_combined_params[1], away_combined_params[2])
# 
#             # Determine pairwise whether or not home_win, away_win, or tie across
#             # the N_SIMS:
#             sim_outcomes <- ifelse(away_runs + home_runs == 0, "NRFI","YRFI")
# 
#             # Return a tibble that has the match id, actual outcome, and predicted probs
#             # for each of the outcomes:
#            tibble(game_pk = game_i_data$game_pk,
#                    outcome = game_i_data$total_runs,
#                    NRFI_win_prob = length(which(sim_outcomes == "NRFI")) / N_SIMS,
#                    NRFI_lose_prob = length(which(sim_outcomes == "YRFI")) / N_SIMS)
#             
#           })
# 
# pred_game_outcomes





```






