---
title: "NRFI Models"
author: "Devin Basley"
date: "2024-04-02"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)

```

# Load Data

```{r}
# Load first inning data
statcast_2023_first_inning <- read_csv("~/Downloads/Sports Analytics/NRFI/statcast_2023_first_inning.csv")
 
# Checks to see all events of data
table(statcast_2023_first_inning$events)

# Vector of Events that only include action events
# Balls and Strikes that DO NOT result in walks or strikeouts excluded
included_events <- c("double", "field_out", "force_out",
                     "home_run", "sac_fly", "strikeout", "walk",
                     "double_play", "fielders_choice",
                     "sac_fly_double_play",
                     "strikeout_double_play", "field_error",
                     "fielders_choice_out", "hit_by_pitch", "sac_bunt", "single",
                     "triple")


# Filter statcast data for only action events
statcast_2023_first_inning <- statcast_2023_first_inning %>%
  filter(events %in% included_events) %>%
  mutate(total_runs = post_away_score + post_home_score)

na.omit(statcast_2023_first_inning)


# Filter for Top First Inning Score
top_first_inning <- statcast_2023_first_inning %>%
  filter(inning_topbot == "Top")
  
# Filter for Bottom First Inning Score
bot_first_inning <- statcast_2023_first_inning %>%
  filter(inning_topbot == "Bot")



# Distrubition of Away Team First Inning Runs Scored
statcast_2023_first_inning %>%
  ggplot(aes(x = away_score)) +
  geom_histogram() +
  labs(x = "Away Score Before Each Pitch",
       title = "Distribution of Runs After Each Pitch in Top 1st Inning") +
  theme_bw()

# Distribution of Home Team First Inning Runs Scored
statcast_2023_first_inning %>%
  ggplot(aes(x = home_score)) +
  geom_histogram() +
  labs(x = "Home Score Before Each Pitch",
       title = "Distribution of Runs After Each Pitch in Bot 1st Inning") +
  theme_bw()




```

Poisson Distribution or Negative Binomial Distribution???



# Model setup Ideas


## Total runs first inning

```{r}


library(rstanarm)

first_inning_runs <- stan_glmer(total_runs ~ (1 | pitcher) + (1 | batter),
                                family = "Poisson",
                                data = statcast_2023_first_inning)




```


## Top First and Bottom First separate

```{r}

top_first_inning_runs <- stan_glmer(post_away_score ~ (1 | pitcher) + (1 | batter),
                                family = "Poisson",
                                data = top_first_inning)


bot_first_inning_runs <- stan_glmer(post_home_score ~ (1 | pitcher) + (1 | batter),
                                family = "Poisson",
                                data = bot_first_inning)



```


# 


