---
title: "Bayesian Regression"
author: "Devin Basley"
date: "2024-04-22"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)


```

# Data and Data Cleaning

```{r}

# Load Data
statcast_2023_first_inning <- read_csv("statcast_2023_first_inning.csv")


#
statcast_2023_first_inning$on_1b[is.na(statcast_2023_first_inning$on_1b)] <- "woo"
statcast_2023_first_inning$on_2b[is.na(statcast_2023_first_inning$on_2b)] <- "woo"
statcast_2023_first_inning$on_3b[is.na(statcast_2023_first_inning$on_3b)] <- "woo"

#statcast_2023_first_inning <- statcast_2023_first_inning[rev(1:nrow(statcast_2023_first_inning)), ]

# Vector of Events that only include action events
# Balls and Strikes that DO NOT result in walks or strikeouts excluded
included_events <- c("double", "field_out", "force_out",
                     "home_run", "sac_fly", "strikeout", "walk",
                     "double_play", "fielders_choice",
                     "sac_fly_double_play",
                     "strikeout_double_play", "field_error",
                     "fielders_choice_out", "hit_by_pitch", "sac_bunt", "single",
                     "triple")


# Filter statcast data for only action events
statcast_2023_first_inning <- statcast_2023_first_inning %>%
  filter(events %in% included_events) %>%
  mutate(runs_before = away_score + home_score)


# # Summarize half inning totals
half_innings <- statcast_2023_first_inning %>%
   group_by(inning_topbot) %>%
   summarize(outs_inning = sum(outs_when_up),
             runs_inning = sum(post_bat_score),
             runs_start = first(runs_before),
             max_runs = runs_inning + runs_start)




statcast_2023_first_inning <- statcast_2023_first_inning %>%
  inner_join(half_innings, by = "inning_topbot") %>%
  mutate(runs_roi = max_runs - runs_before)


# Start Game State compuation
statcast_2023_first_inning <- statcast_2023_first_inning %>%
  mutate(bases = paste0(
    if_else(on_1b == "woo", 0, 1),
    if_else(on_2b == "woo", 0, 1),
    if_else(on_3b == "woo", 0, 1)))
    

# Compute Pre and Post AB State
statcast_2023_first_inning <- statcast_2023_first_inning %>%
  mutate(state = paste(bases, outs_when_up),
        new_state = case_when(
          inning_topbot != lag(inning_topbot) ~ NA_character_,
           TRUE ~ lag(state)
         ))



# Reverse Data
statcast_2023_first_inning <- statcast_2023_first_inning[rev(1:nrow(statcast_2023_first_inning)), ]


statcast_2023_first_inning$new_state[is.na(statcast_2023_first_inning$new_state)] <- "woo"

statcast_2023_first_inning <- statcast_2023_first_inning %>%
  mutate(new_state = str_replace(new_state, "woo", "3"))


# End of First Inning Summary
end_inning_data <- statcast_2023_first_inning %>%
  dplyr::select(c(game_date, game_pk, player_name, player_name, batter, post_home_score, post_away_score, inning_topbot, away_team, home_team)) %>%
  group_by(game_pk) %>%
  mutate(away_runs = max(post_away_score),
            home_runs = max(post_home_score),
            total_runs = away_runs + home_runs,
            home = home_team,
            away = away_team) %>%
  ungroup() 
  
# Home team indicator variable
end_inning_data <- end_inning_data %>%
  mutate(is_home = ifelse(inning_topbot == "Bot", 1, 0)) 

end_inning_data <- end_inning_data %>%
  mutate(team = if_else(is_home == 1, home, away),
         runs = if_else(is_home == 1, home_runs, away_runs)) 


# Selecting required columns
new_dataset <- end_inning_data %>%
  dplyr::select(game_pk, team, runs, is_home, player_name)

half_inning_summary <- end_inning_data %>%
  group_by(game_pk, is_home) %>%
  summarise(team = first(team),
            runs = if_else(first(is_home) == 1, max(home_runs), max(away_runs)),
            pitcher = first(player_name),
            PA = n_distinct(batter),
            date = first(game_date)) %>%
  ungroup()

team_info <- end_inning_data %>%
  group_by(game_pk) %>%
  summarise(home_team = first(home),
            away_team = first(away)) %>%
  ungroup()



# Merge team information with half_inning_data
half_inning_data <- half_inning_summary %>%
  left_join(team_info, by = "game_pk")


inning_summary <- half_inning_data %>%
  group_by(game_pk) %>%
  summarize(
    home_team = first(home_team),
    away_team = first(away_team),
    home_runs = sum(if_else(is_home == 1, runs, 0)),
    away_runs = sum(if_else(is_home == 0, runs, 0)),
    total_runs = if_else(home_runs + away_runs == 0, "NRFI", "YRFI"),
    date = first(date)
  ) %>%
  ungroup()



```

```{r}
#pitch types feature

raw <- read_csv("statcast_2023_first_inning.csv")

pitch_types <- raw %>%
  group_by(game_date, player_name, pitch_type) %>%
  summarize(pitch_count = n()) %>%
  ungroup() %>%
  spread(pitch_type, pitch_count, fill = 0)

pitch_types$total <- rowSums(pitch_types[, -c(1, 2)])

#create proportions of pitch types thrown
pitch_types_x <- pitch_types %>%
  mutate(across(starts_with("CH"):starts_with("SV"), ~ .x / total)) %>%
  select(-total)

#join back to main dataset (half_inning_data)
half_inning_data <- half_inning_data %>%
  left_join(pitch_types_x, by = c("pitcher" = "player_name", "date" = "game_date"))

#get rid of NA column
half_inning_data <- half_inning_data[, 1:24]

#rule: if mean is greater than 0.01, keep pitch type, otherwise exclude it
#exclude CS, FA, FO, KN, PO, SV
half_inning_data <- half_inning_data %>%
  select(-c(CS, FA, FO, KN, PO, SV))
```

```{r}
#pitcher spin rate and release extension feature
spins <- raw %>% 
  group_by(player_name) %>% 
  summarize(spin_rate = mean(release_spin_rate, na.rm = TRUE)) %>% 
  ungroup()
#join back to main dataset (half_inning_data)
half_inning_data <- half_inning_data %>% 
  left_join(spins, by = c("pitcher" = "player_name"))
```

```{r}
#park factors
library(baseballr)

park <- fg_park("2023")
#add a new column with the 3 letter abbreviation of the baseball team
park$team <- park$home_team
park$team <- replace(park$team, park$team == "Diamondbacks", "ARI")
park$team <- replace(park$team, park$team == "Braves", "ATL")
park$team <- replace(park$team, park$team == "Orioles", "BAL")
park$team <- replace(park$team, park$team == "Red Sox", "BOS")
park$team <- replace(park$team, park$team == "White Sox", "CWS")
park$team <- replace(park$team, park$team == "Cubs", "CHC")
park$team <- replace(park$team, park$team == "Reds", "CIN")
park$team <- replace(park$team, park$team == "Indians", "CLE")
park$team <- replace(park$team, park$team == "Rockies", "COL")
park$team <- replace(park$team, park$team == "Tigers", "DET")
park$team <- replace(park$team, park$team == "Astros", "HOU")
park$team <- replace(park$team, park$team == "Royals", "KC")
park$team <- replace(park$team, park$team == "Angels", "LAA")
park$team <- replace(park$team, park$team == "Dodgers", "LAD")
park$team <- replace(park$team, park$team == "Marlins", "MIA")
park$team <- replace(park$team, park$team == "Brewers", "MIL")
park$team <- replace(park$team, park$team == "Twins", "MIN")
park$team <- replace(park$team, park$team == "Mets", "NYM")
park$team <- replace(park$team, park$team == "Yankees", "NYY")
park$team <- replace(park$team, park$team == "Athletics", "OAK")
park$team <- replace(park$team, park$team == "Phillies", "PHI")
park$team <- replace(park$team, park$team == "Pirates", "PIT")
park$team <- replace(park$team, park$team == "Padres", "SD")
park$team <- replace(park$team, park$team == "Giants", "SF")
park$team <- replace(park$team, park$team == "Mariners", "SEA")
park$team <- replace(park$team, park$team == "Cardinals", "STL")
park$team <- replace(park$team, park$team == "Rays", "TB")
park$team <- replace(park$team, park$team == "Rangers", "TEX")
park$team <- replace(park$team, park$team == "Blue Jays", "TOR")
park$team <- replace(park$team, park$team == "Nationals", "WSH")

#join back to main dataset (half_inning_data)
park <- park[, c(2, 4, 5)]
half_inning_data <- half_inning_data %>% 
  left_join(park, by = c("home_team" = "home_team"))
```


# Bayesian Poisson Model


```{r}

library(rstanarm)
options(mc.cores = parallel::detectCores())
team_runs_model <- stan_glmer(runs ~ is_home + (1 | home_team) + (1 | away_team),
                              family = poisson,
                              data = half_inning_data,
                              cores = 8,
                              iter = 2000 * 2,
                              seed = 2015,
                              chains = 4)


```

# Bayesian Poisson Regression Predictions

```{r}


nrfi_preds <- posterior_predict(team_runs_model, newdata = half_inning_data, seed = 2023)

nrfi_preds_home <- posterior_predict(team_runs_model, newdata = tibble(home_team = "CLE",
                                                                  away_team = "SEA",
                                                                  is_home = 1), seed = 15)
nrfi_preds_away <- posterior_predict(team_runs_model, newdata = tibble(home_team = "CLE",
                                                                  away_team = "SEA",
                                                                  is_home = 0), seed = 15)

hist(nrfi_preds_home, main = "CLE Runs vs SEA", 
     xlab = "# of Runs")

hist(nrfi_preds_away, main = "SEA Runs vs CLE", 
     xlab = "# of Runs")



```


# Bayesian Logistic Regression

```{r}

nrfi_model_logit <- stan_glmer(as.factor(total_runs) ~ (1 | home_team) + (1 | away_team),
                              family = binomial,
                              data = inning_summary,
                              cores = 8,
                              iter = 2000 * 2,
                              seed = 2015,
                              chains = 4)


nrfi_logit_preds <- posterior_predict(nrfi_model_logit,
                                      newdata = tibble(home_team = "CLE",
                                                       away_team = "SEA"),
                                      seed = 20)

nrfi_logit_preds_test <- posterior_predict(nrfi_model_logit,
                                      newdata = tibble(home_team = "SEA",
                                                       away_team = "CLE"),
                                      seed = 20)

cat("Probability of NRFI between CLE (home) and SEA (away)", sum(nrfi_logit_preds == 0) / length(nrfi_logit_preds) * 100, "%")

cat("Probability of NRFI between SEA (home) and CLE (away)", sum(nrfi_logit_preds_test == 0) / length(nrfi_logit_preds_test) * 100, "%")


```



